### ISSUE TITLE
`AttributeError: module 'cffi' has no attribute 'FFI'` in version 2.0.0

### ISSUE THREAD

**Issue by map0logo** [python-cffi/cffi#222]
### **Description:**

After upgrading to **cffi v2.0.0**, downstream libraries (notably `statsmodels`) are failing because `cffi.FFI` is no longer accessible as a top-level attribute of the `cffi` module.

In version 1.x, it was standard to initialize the interface via `cffi.FFI()`. In v2.0.0, this now raises an `AttributeError`.

We are seeking clarification on whether this is an intentional breaking change for the 2.0.0 roadmap (requiring downstream updates) or an unintended packaging/export issue.

### **Environment:**

* **cffi version:** 2.0.0
* **Python version:** 3.12
* **OS:** Manjaro Linux

### **Steps to Reproduce:**

```python
import cffi
print(f"CFFI Version: {cffi.__version__}")

# This worked in 1.17.x, but fails in 2.0.0
try:
    ffi = cffi.FFI()
    print("Successfully initialized FFI")
except AttributeError as e:
    print(f"Error: {e}")

```

### **Observed Behavior:**

```text
CFFI Version: 2.0.0
Error: module 'cffi' has no attribute 'FFI'

```

### **Impact:**

This currently breaks `statsmodels.stats.multicomp.pairwise_tukeyhsd`, which is widely used in the scientific Python ecosystem (often within JupyterLab environments where `cffi` is a transitive dependency).

**Traceback from statsmodels:**

```text
File ".../statsmodels/stats/multicomp.py", line 123, in pairwise_tukeyhsd
    ffi = cffi.FFI()
AttributeError: module 'cffi' has no attribute 'FFI'

```

### **Questions:**

1. Is `cffi.FFI` intentionally moved or removed in v2.0.0?
2. Is there a new recommended way to instantiate the FFI object (e.g., a specific sub-module import)?
3. Should downstream maintainers pin `cffi < 2.0.0` for compatibility?

**Comment by mattip** [comment]
Please start with how you installed statmodels, how you created your python environment.

**Comment by mattip** [comment]
That does not answer the question. How did you install whatever you are using? This is not a problem with cffi, rather something has gone wrong with your environment. Perhaps you have a partial installation somehow, have deleted parts, or have some other cffi.py installed. You will have to dive deeper in order to figure out what is wrong.

**Comment by map0logo** [comment]
This issue happens in SciPy.

line 12 of "scipy/lib/_ccallback.py"

```python
def _import_cffi():
    global ffi, CData

    if ffi is not None:
        return

    try:
        import cffi
        ffi = cffi.FFI()
        CData = ffi.CData
    except ImportError:
        ffi = False
```

This function expects that the module `cffi` has an `FFI` attribute.

cffi version 2.0.0
```python
>>> cffi.FFI()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'cffi' has no attribute 'FFI'
>>> cffi.__version__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'cffi' has no attribute '__version__'
```

cffi version 1.17.1

```python
>>> import cffi
>>> cffi.FFI()
<cffi.api.FFI object at 0x7f2108a29490>
>>> cffi.__version__
'1.17.1'
```

**Comment by mattip** [comment]
Can we close this?
